name: nice_hooks
description: A Package for all the Shared Code in Nice One, Nice Two, Nice Admin
version: 0.0.3
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.1
  intl: ^0.17.0
  path_provider: ^2.0.11
  share_plus: ^6.3.0
  syncfusion_flutter_charts: ^20.3.58

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
