part of nice_hooks;

List<String>? routes;

List<String> getRoutes(String region) {
  if (region == "Central 1") {
    routes = [
      //Confirmed
      "Ware House",
      "Kajjansi",
      "Kawuku",
      "Salaama Makindye",
      "Busabala Gangu Kibiri",
      "Abayita Ababiri",
      "Kasanga Kabalagala",
      "Kibuli",
      "Busega kyengera",
      "Kasubi Namugoona",
      "Nansana wakiso",
      "Bulega Buloba ",
      "Natete",
      "Mengo",
      "Seroma",
      "Nkrumah road",
      "Nasser road",
      "Container Village",
      "Owino",
      "Kisenyi",
      "New tax park",
      "Tradelink",
      "Superior",
      "God's grace",
      "Giant",
      "Boost",
      "Kati kati",
      "Discount mall",
      "Cornerstone",
      "Kikuubo",
      "Kafumbe Mukasa",
      "Arua Park",
      "Nakasero",
      "Kampala Road",
    ];
  } else if (region == "Central 2") {
    routes = [
      //Confirmed
      "Ware House",
      "Gayaza",
      "Nakawa",
      "Kawempe",
      "Luwero",
      "Luzira",
      "Ntinda",
      "Mukono",
      "Seeta",
      "Kayunga",
      "Lugazi",
      "Kireka",
      "Manyagwa",
      "Nakasanja",
      "Nakwero",
      "Kyabakade",
      "Ngoma",
      "Nakasongola Town",
      "zengebe Landing Site",
      "Lwampanga Landing Site",
      "Luwero CBD",
      "Luwero High Way Route",
      "Kasana Kikubo Route",
      "Katikamu Route",
      "Kikyusa Route",
      "Testing Route",
    ];
  } else if (region == "North") {
    routes = [
      // Confirmed
      "Ware House",
      "Town Service Gulu CBD",
      "Unyama Paicho Cwero",
      "Koro Palenga Bobi",
      "Koch Goma Anaka",
      "Lacor Pabbo Atiak",
      "Amugo Alebtong Aloi",
      "Otuke",
      "Kole",
      "Alito Agwata Aduku",
      "Lira CBD",
      "Dokolo Amolatar",
      "Kitgum Town",
      "Kalongo",
      "Mubyubunyu",
      "Acholi Bur",
      "Lamwo",
      "Aduku Apac",
      "Alebtong Patongo",
      "Odokomit Bala",
      "Adjumani CBD",
      "Laropi",
      "Onzimai",
      "Pagirinya",
    ];
  } else if (region == "East") {
    routes = [
      "Ware House",
      "Jinja Town Service",
      "Mbale Town Service",
      "Kumi Town Service",
      "Soroti Town Service",
      "Moroto Town SERVICE",
      "Tororo Town Service",
      "Iganga Town Service",
      "Bugiri Town Service",
      "Bugiri Town Iddudi Busowa",
      "Bugiri Town Namayemba Buwumi Muwayo",
      "Kamuli Town Service",
      "Mbale Busamaga",
      "Mbale Kapochorwa",
      "Mbale Kachumbale",
      "Mbale Tirinyi",
      "Mbale Pallisa",
      "Mbale Kamunkoli Budaka Tirinyi Palisa",
      "Kumi Mukula Ngora",
      "Kumi Bukedea Kachumbala",
      "Kumi Ongeno",
      "Kumi Atutur",
      "Kumi Mukongoro",
      "Kumi Tirinyi Palisa Kadama",
      "Soroti Serere",
      "Soroti Amuria",
      "Soroti Katakwi",
      "Soroti Kaberamaido",
      "Tororo Nagongera",
      "Tororo Malaba",
      "Tororo Magodesi",
      "Iganga Namungalwe Nabaale Kaliro",
      "Iganga Namutumba Busembatya",
      "Iganga Musiita Mayuge",
      "Centers Bugamaga Nkoma Nakalore",
      "Centers Namusi Sironko Kapchorwa",
      "Centers Nyeru Ogooma Ngora",
      "Centers Ogeno Mukula",
      "Centers Aturur",
      "Centers Makongoro Kanyum",
      "Centers Camp Swahili Odudai Asamuk",
      "Centers Milo5 Milo8",
      "Bugembe Magamaga",
      "Wanyange Bugembe Kakira",
      "Nawansaso Namwendwa",
      "Kasambira Buwenge",
      "Balawoli Bukungu",
      "Mafubira Mpumudde Namulesa",
      "Mbiiko Nakibizi Kitigoma",
      "Busia Lumino",
      "Palisa Mukongero",
      "Makongoro",
      "Nakapiripiriti",
      "Bulanga Musiita Lugolele",
    ];
  } else if (region == "South West") {
    routes = [
      //Confirmed
      "Ware House",
      "Bugongi Kitagata",
      "Masheruka Kanyeganyege Buhwe",
      "Rwentuha nyakabirizi",
      "Kashaka itendero",
      "Kabwohe Town Service",
      "TownService Nyeihanga",
      "Rwentuha Katerera-Bunya",
      "Rwentuha Nyakabirizi",
      "Bunyaruguru Bushenyi",
      "Kabale Kisoro",
      "Kabale Mwanjali To Rwa",
      "Kabale Town Service",
      "Kabale Muhanga",
      "Lukaya Nyendo",
      "Kyotera Kalisizo",
      "Lyantonde Route",
      "Masaka Town",
      "Bukomansimbi",
      "Kirimaya",
      "Bukunda",
      "Kasensero",
      "Kakuto",
      "Mutukula",
      "Rakai",
      "Sembabule",
      "Ishaka Town Kizinda",
      "KIU Bushenyi",
      "ISHAKA TOWN SERVICE",
      "Kashenshero Mitoma Route",
      "Mbarara Town",
      "Biharwe Koranorya Sanga",
      "Kaberebere Isingiro Nakivale",
      "Mbarara Katete Ruharo",
      "Nyamukana",
      "Ntare Road Rwebikona",
      "Ntungamo",
      "Rubaare",
      "Rukungiri",
      "Bwizibwera",
      "Rubindi",
      "Ruti",
      "Nyeihanga",
      "Ibanda Town",
      "Kamwenge Town",
      "Inshongororo",
      "Igorora",
      "Mateete",
      "Rwemiyaga",
      "Mbirizi",
      "Kyazanga",
      "Katovu",
      "Kabundi",
      "Ntusi",
      "Kambuga",
      "Kanungu",
      "Kihihi",
      "Nyakibale",
      "Buyanja",
      "Kagarama",
      "Ruhama-Mirama hill",
      "Kafunjo",
      "Kitwe"
    ];
  } else if (region == "West Nile") {
    routes = [
      //Confirmed
      "Ware House",
      "Arua CBD",
      "Awindiri",
      "Onduparaka",
      "Rhino Camp",
      "Kiboko CBD",
      "Odramacaku",
      "Lokiria Godo",
      "Ariwara",
      "Ayivu",
      "Lodonga",
      "Midogo",
      "Swinga",
      "Merwa",
      "Yumbe Town",
      "Payini",
      "Panyamur",
      "Dei",
      "Patent",
      "Parombo",
      "Nyalepi",
      "Nebbi",
      "Paidha",
      "Erusi",
      "Panyimur",
      "Pokwero",
      "Madi Okollo",
      "Nyaravur",
      "Patenge",
      "Pawor",
      "Pakwach",
    ];
  } else if (region == "Mid West") {
    routes = [
      //Confirmed
      "Ware House",
      "Kyangwali",
      "Kaiso Tonya",
      "Buliisa",
      "Kigorobya",
      "Kibale Kisiita",
      "Kigumba",
      "Karuma",
      "Bundibugyo",
      "Kyenjojo",
      "Bwera",
      "Bunyaruguru",
      "Rwimi",
      "Lwamata Bukomero",
      "Kyankwanzi",
      "Ntwetwe",
      "Rugombe",
      "Mukunyu",
      "Kisiita",
      "Katikara",
      "Mubende CBD",
      "Mubende HIGHWAY",
      "Kyengegwa",
      "Kakumiro",
      "Kasanda-Bukuya",
      "Mandela",
      "Butyaba Road",
      "Kilyatete",
      "Kinubi",
      "Kisita",
      "Buhimba",
      "Kabwoya",
      "Kizila Nfumbi",
      "Pakanyi",
      "kyatiri",
      "Dima Gulu highway"
    ];
  } else if (region == "Supermarkets") {
    routes = [
      "Entebbe Road",
      "Nsambya",
      "Kansanga",
      "Muyenga",
      "Bunga",
      "Buziga",
      "Kamwokya",
      "Ntinda",
      "Nakawa",
      "Kiwatule",
      "Naalya",
      "Kiira",
      "Kisasi",
      "Kyanja",
      "Bugolobi",
      "Kitintale",
      "Mpererwe",
      "Kawempe",
      "Gayaza",
      "Mukono",
      "Kampala Town",
      "Jinja Road",
      "Nansana Wakiso",
      "Nambole Kirinya",
      "Luzira"
    ];
  }
  return routes!;
}
